"""Controlled Q1 reference-template changes with immutable material particles.

Geometry-only proposals may be incompatible with Fp. They are diagnostic until
the inherited strict history check accepts them. No projection overwrites Fp.
"""
import itertools
import time
import numpy as np
from scipy import sparse
from scipy.sparse.linalg import eigsh, splu

from .consistent_transfer import MaterialQ1, Samples, CORNERS, material_response


class RemappedQ1(MaterialQ1):
    def __init__(self, source, axes, order=3):
        start = time.perf_counter()
        self.axes = tuple(np.array(a, dtype=float, copy=True) for a in axes)
        if len(self.axes)!=3 or any(len(a)<2 or not np.isfinite(a).all() or np.any(np.diff(a)<=0) for a in self.axes):
            raise ValueError('three finite strictly increasing knot arrays required')
        self.lo = source.lo.copy()
        high = source.lo+source.h*source.counts
        if any(abs(a[0]-lo)>1e-12 or abs(a[-1]-hi)>1e-12 for a,lo,hi in zip(self.axes,self.lo,high)):
            raise ValueError('template change must preserve the reference material domain')
        self.counts = np.array([len(a)-1 for a in self.axes])
        self.shape = tuple(self.counts+1)
        self.h = source.h  # only a reporting scale; all geometry uses actual axes
        self.X = np.array(list(itertools.product(*self.axes)))
        self.fixed = np.isclose(self.X[:,0],self.lo[0],atol=1e-14,rtol=0)
        self.free = ~self.fixed
        self.field, self.params = source.field, source.params
        self.particles = self.sample(source.particles.X.copy(),source.particles.weight.copy())
        # Particle orientation is authoritative, not regenerated by a new group.
        self.particles.A[:] = source.particles.A
        self.mass = source.mass.copy()
        self.quadrature = self.rule(order,gauss=True)
        self.map_seconds = time.perf_counter()-start
        start = time.perf_counter()
        N = self.particles.N
        self.M = (N.T@N.multiply(self.mass[:,None])).tocsc()
        self.lumped = np.asarray(N.T@self.mass).ravel()
        if N.shape[1]>N.shape[0]:
            raise ValueError('new template has more scalar unknowns than particle observations')
        # A constant start can be exactly orthogonal to alternating null modes.
        # Use a reproducible nonsymmetric start and retain a factorization gate.
        seed=np.random.default_rng(381).normal(size=len(self.X))
        emax = eigsh(self.M,k=1,which='LA',return_eigenvectors=False,tol=1e-8,v0=seed)[0]
        emin = eigsh(self.M,k=1,which='SA',return_eigenvectors=False,tol=1e-8,v0=seed)[0]
        if emin<=1e-12*emax:
            raise ValueError('new template mass is rank deficient; no silent regularization')
        self.mass_eigenvalues = np.array([emin,emax])
        try:
            self.factor = splu(self.M)
            self.free_factor = splu(self.M[self.free][:,self.free].tocsc())
        except RuntimeError as exc:
            raise ValueError('new template mass is rank deficient; factorization rejected') from exc
        self.mass_seconds = time.perf_counter()-start

    def sample(self,X,weights):
        X = np.asarray(X,dtype=float)
        if any(np.any(X[:,d]<a[0]-1e-12) or np.any(X[:,d]>a[-1]+1e-12) for d,a in enumerate(self.axes)):
            raise ValueError('material sample outside reference domain')
        cells = np.column_stack([np.clip(np.searchsorted(a,X[:,d],side='right')-1,0,len(a)-2) for d,a in enumerate(self.axes)])
        low = np.column_stack([a[cells[:,d]] for d,a in enumerate(self.axes)])
        width = np.column_stack([a[cells[:,d]+1]-a[cells[:,d]] for d,a in enumerate(self.axes)])
        q = (X-low)/width
        f = np.where(CORNERS[None]==1,q[:,None],1-q[:,None])
        vertices = cells[:,None]+CORNERS
        ids = np.ravel_multi_index(vertices.reshape(-1,3).T,self.shape)
        rows = np.repeat(np.arange(len(X)),8)
        shape = (len(X),len(self.X))
        N = sparse.coo_matrix((f.prod(2).ravel(),(rows,ids)),shape=shape).tocsr()
        D=[]
        for d in range(3):
            v=(2*CORNERS[None,:,d]-1)*f[:,:,[j for j in range(3) if j!=d]].prod(2)/width[:,d,None]
            D.append(sparse.coo_matrix((v.ravel(),(rows,ids)),shape=shape).tocsr())
        angle=np.zeros(len(X))
        if self.field=='smooth':angle=(X[:,1]-.4375)/.125*np.pi/2
        elif self.field=='crossed':angle=np.where(X[:,1]>=.5,np.pi/2,0.)
        a=np.column_stack((np.cos(angle),np.sin(angle),np.zeros(len(X))))
        return Samples(X,np.asarray(weights),N,tuple(D),np.einsum('qi,qj->qij',a,a))

    def rule(self,order,gauss=True):
        if order<2 or not gauss:raise ValueError('template quadrature requires Gauss order >=2')
        z,w=np.polynomial.legendre.leggauss(order)
        q=np.array(list(itertools.product(z,repeat=3)))
        ww=np.prod(np.array(list(itertools.product(w,repeat=3))),axis=1)/8
        points=[];weights=[]
        for cell in itertools.product(*[range(n) for n in self.counts]):
            lo=np.array([a[i] for a,i in zip(self.axes,cell)])
            hi=np.array([a[i+1] for a,i in zip(self.axes,cell)])
            points.append((hi+lo)/2+q*(hi-lo)/2);weights.append(ww*np.prod(hi-lo))
        return self.sample(np.concatenate(points),np.concatenate(weights))

    def propose(self,positions,boundary_positions):
        """Constrained geometry fit; does not modify particles or deformation."""
        rhs=self.particles.N.T@(self.mass[:,None]*positions)
        x=np.zeros_like(self.X);x[self.fixed]=boundary_positions
        x[self.free]=self.free_factor.solve(rhs[self.free]-self.M[self.free][:,self.fixed]@boundary_positions)
        return x


def axes_for(source,kind):
    axes=[source.lo[d]+np.arange(source.counts[d]+1)*source.h for d in range(3)]
    if kind=='identity':return axes
    if kind=='refine_x':axes[0]=np.sort(np.r_[axes[0],(axes[0][:-1]+axes[0][1:])/2])
    elif kind=='shift':
        axes=[a+.2*source.h*np.sin(np.linspace(0,np.pi,len(a))) for a in axes]
    elif kind=='coarsen_x':axes[0]=axes[0][::2]
    else:raise ValueError('unknown template change')
    return axes


def common_rule(old,new,order=3):
    """Split at every old/new knot to separate remapping from rule changes."""
    axes=[np.unique(np.round(np.r_[old.lo[d]+np.arange(old.counts[d]+1)*old.h,new.axes[d]],14)) for d in range(3)]
    z,w=np.polynomial.legendre.leggauss(order)
    q=np.array(list(itertools.product(z,repeat=3)));ww=np.prod(np.array(list(itertools.product(w,repeat=3))),axis=1)/8
    points=[];weights=[]
    for cell in itertools.product(*[range(len(a)-1) for a in axes]):
        lo=np.array([a[i] for a,i in zip(axes,cell)]);hi=np.array([a[i+1] for a,i in zip(axes,cell)])
        points.append((hi+lo)/2+q*(hi-lo)/2);weights.append(ww*np.prod(hi-lo))
    return np.concatenate(points),np.concatenate(weights)


def weighted_relative(delta,reference,weights):
    a=np.sum(np.asarray(delta).reshape(len(weights),-1)**2,axis=1)
    b=np.sum(np.asarray(reference).reshape(len(weights),-1)**2,axis=1)
    return float(np.sqrt(weights@a/max(weights@b,1e-30)))


def audit_remap(old,new,xold,positions,Fp):
    """A diagnostic proposal; strict dynamic acceptance is independent of size."""
    start=time.perf_counter();audit_start=start
    boundary=old.sample(new.X[new.fixed],np.ones(new.fixed.sum())).N@xold
    proposal=new.propose(positions,boundary)
    recovery_seconds=time.perf_counter()-start
    Fnew=new.gradient(new.particles,proposal)
    psi0,P0=material_response(Fp,old.particles.A,old.params)
    psi1,P1=material_response(Fnew,new.particles.A,new.params)
    sigma0=P0@Fp.transpose(0,2,1)/np.linalg.det(Fp)[:,None,None]
    sigma1=P1@Fnew.transpose(0,2,1)/np.linalg.det(Fnew)[:,None,None]
    C0=Fp@old.particles.A@Fp.transpose(0,2,1)
    C1=Fnew@new.particles.A@Fnew.transpose(0,2,1)
    C0/=np.trace(C0,axis1=1,axis2=2)[:,None,None]
    C1/=np.trace(C1,axis1=1,axis2=2)[:,None,None]
    points,weights=common_rule(old,new)
    before=old.sample(points,weights);after=new.sample(points,weights)
    F0=old.gradient(before,xold);F1=new.gradient(after,proposal)
    e0=material_response(F0,before.A,old.params)[0];e1=material_response(F1,after.A,new.params)[0]
    U0=float(weights@e0);U1=float(weights@e1)
    Uold=old.elastic(xold)[0];Unew=new.elastic(proposal)[0]
    try:
        new.recover(positions,Fp)
        accepted=True;reason='strict particle geometry/F compatibility passed'
    except ValueError as exc:
        accepted=False;reason=str(exc)
    record=dict(common_energy_before=U0,common_energy_after=U1,remap_energy_delta=U1-U0,
                remap_energy_relative=(U1-U0)/max(abs(U0),1e-30),
                absolute_local_energy_change_relative=float(weights@abs(e1-e0)/max(abs(U0),1e-30)),
                particle_energy_relative=float(old.particles.weight@(psi1-psi0)/max(old.particles.weight@psi0,1e-30)),
                own_rule_total_delta=Unew-Uold,rule_change_delta=(Unew-Uold)-(U1-U0),
                position_rms=float(np.sqrt(np.average(np.sum((new.particles.N@proposal-positions)**2,axis=1),weights=old.mass))),
                strain_relative=weighted_relative(Fnew.transpose(0,2,1)@Fnew-Fp.transpose(0,2,1)@Fp,
                                                  Fp.transpose(0,2,1)@Fp-np.eye(3),old.mass),
                stress_relative=weighted_relative(sigma1-sigma0,sigma0,old.mass),
                current_direction_tensor_relative=weighted_relative(C1-C0,C0,old.mass),
                min_det=float(np.linalg.det(Fnew).min()),dynamic_accepted=accepted,reason=reason,
                recovery_seconds=recovery_seconds,map_seconds=new.map_seconds,mass_seconds=new.mass_seconds,
                nodes=len(new.X),particles=len(new.mass),material_samples=len(new.quadrature.X),
                min_mass_eigenvalue=float(new.mass_eigenvalues[0]),
                diagnostic_audit_seconds=time.perf_counter()-audit_start)
    return proposal,record


def audit_mode(old,new,mode):
    particles=old.particles.N@mode
    fitted=new.project(particles,clamped=True)
    dF0=old.gradient(old.particles,mode);dF1=new.gradient(new.particles,fitted)
    return dict(increment_relative=weighted_relative(dF1-dF0,dF0,old.mass),
                displacement_relative=weighted_relative(new.particles.N@fitted-particles,particles,old.mass))
